version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - ./scrapedata:/app/scrapedata
      - ./results.csv:/app/results.csv
    environment:
      - FLASK_ENV=development